# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 269e4b8951d3ef7cb97ccaeff73c49e6bba453884ec5a186e7c485e9560b34a1b397063485d0122033afa03180dc1583a31a1a2b38da29052fbcca035caba692

test:
  secret_key_base: b771a83055e78570123d99503bc60e7da1f4f4803732d85b48433b7c71f057b688029905ca4306f72fba68d415c8b8ac25817fb8c35dd3b6dc148fc9a7782177

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
